### ISSUE TITLE
password and keys hard coded

### ISSUE THREAD

**Issue by shawndwells** [CrowdStrike/zscaler-FalconX-integration#1]
https://github.com/CrowdStrike/zscaler-FalconX-integration/blob/5088e3ddc195933fddaaf67a62c09be7b82d7308/ZScaler_Intel_Bridge_config.py#L22

**Comment by shawndwells** [comment]
Bump @ckachigian

**Comment by ckachigian** [comment]
Yes, those were deleted.  A Git history reset is needed.

**Comment by shawndwells** [comment]
Reset the history
