### ISSUE TITLE
Private IP addresses exclusions

### ISSUE THREAD

**Issue by CyberHygiene101** [CrowdStrike/zscaler-FalconX-integration#12]
Hi,

~10% of the custom URLs contain private IP addresses which are unlikely to be applicable for most environments.

The current count of total URLs from CS-->ZScaler is ~23,500. This has an impact as the total number of supported URLs is 25,000 based on Zscaler documentation: https://help.zscaler.com/zia/ranges-limitations . The console https://adminurl/#administration/url-categories also displays a message that 25k is the maximum.

Is it possible to have an option in the config file which if enabled, will use a different regex which excludes private IP addresses from the custom URLs being created in Zscaler.

Thank you.

**Comment by menace2001** [comment]
I get a 39.000 .. that seems to be far too much then.. is Reponse 200 good or bad?

Classifying 100 new URLs; Rate limit monitor: 39091/39000
New indicators payload size: 2882/10000.
Approaching rate limit; Removing deleted URLs.
Deleted indicators payload size: 242/10000.
Finished removing deleted URLs; Activating changes.
Committing changes to Zscaler.
Current status of commits for Zscaler: <Response [200]>
200
Activated Changes; Sleeping for 0:47:54.183684 seconds.

**Comment by CyberHygiene101** [comment]
39k is the maximum calls per hour.

I started having the same issue as you, the payload size does not reach 10k, I get a messages saying committing changes to Zscaler but then nothing gets committed Zscaler and the payload starts building up again. 

By changing zs_max_payload_size from 10000 to 100, malicious URLs started populating in Zscaler. You could try that, this might be another bug. 



2022-04-28 11:33:43,148   6024 DEBUG   https://XXXXX:443  "POST /api/v1/urlLookup HTTP/1.1" 200 None
2022-04-28 11:33:44,154   6024 INFO   New indicators payload size: 7060/10000.
2022-04-28 11:33:44,154   6024 INFO   Approaching rate limit; Removing deleted URLs.
2022-04-28 11:33:44,154   6024 INFO   Deleted indicators payload size: 572/10000.
2022-04-28 11:33:44,154   6024 INFO   Finished removing deleted URLs; Activating changes.
2022-04-28 11:33:44,154   6024 INFO   Committing changes to Zscaler.
2022-04-28 11:33:44,154   6024 DEBUG   Starting new HTTPS connection (1): https://XXXXX:443
2022-04-28 11:33:44,844   6024 DEBUG   https://XXXXX:443 "GET /api/v1/status HTTP/1.1" 200 20
2022-04-28 11:33:44,844   6024 INFO   Current status of commits for Zscaler: <Response [200]>

**Comment by menace2001** [comment]
Great, that worked for me too! Thanks for your response!

**Comment by jlangdev** [comment]
@menace2001 @CyberHygiene101 Hey guys, thanks for the info here. I patched the script recently, and it' filters out private IP's now, so there's going to be way less noise. I think changing the max payload size to 100 is really interesting too. I'm going to experiment a bit with smaller max payloads and possibly update the default config if it goes well.

**Comment by CyberHygiene101** [comment]
@jlangdev Thank you. Not sure if you saw my comment on the commit regarding the network masks for Private IPs in the filter which appear to be incorrect. 
https://github.com/CrowdStrike/zscaler-FalconX-integration/commit/5412681e24c88594bb085e9b0ca243042b975b5b
